
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hubspotapp_dev

test:
  <<: *default
  database: hubspotapp_test

production:
  <<: *default
  database: hubspotapp_prod
