# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b68b0305dc0d3992c7c89de7ff1ef3b438ffd33aaca30639c1cf3886964760f45df2030b61ac4a84716ad5960f9ad3fdea493131625267abee771753977855ab

test:
  secret_key_base: 5eaf5f419af858a4d317c38a99b112c77ffc75b6d55ba284fb8d19ba7ff8193152ee64fb05fd3a57ede4072705d82d1debacc1f68e07e3aba397384f9af297cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
